name: pontogov_treinamento

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_php
    ports:
      - "88:80"
    volumes:
      - ./xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./src/:/var/www/html/